# Generated by Django 2.2 on 2020-01-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20200127_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='order',
        ),
    ]
