# Generated by Django 2.2 on 2020-01-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='product',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='servicecontact',
            name='address',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='servicecontact',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='servicecontact',
            name='message',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='servicecontact',
            name='name',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='servicecontact',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
