# Generated by Django 2.2 on 2020-01-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='img/dummy.png', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
