# Generated by Django 2.2 on 2020-01-23 19:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('local_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('size', models.CharField(blank=True, max_length=50)),
                ('pattern', models.CharField(blank=True, max_length=50)),
                ('thickness', models.CharField(blank=True, max_length=50)),
                ('brand_name', models.CharField(blank=True, max_length=100)),
                ('customisable', models.BooleanField(default=False)),
                ('main_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('detail_photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('detail_photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('detail_photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, max_length=800)),
                ('amazon_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('flipkart_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_trending', models.BooleanField(default=False)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('price', models.FloatField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=100)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comment', to='products.Product')),
            ],
        ),
    ]
