# Generated by Django 2.2 on 2020-01-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='comment',
            field=models.TextField(max_length=250),
        ),
    ]
