# Generated by Django 2.2 on 2020-01-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200125_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=1100),
        ),
        migrations.AlterField(
            model_name='product',
            name='pattern',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='thickness',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='comment',
            field=models.TextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
